[build]
  # This is not strictly necessary for functions-only deploys,
  # but good practice if you have a site too.
  # publish = "public" # or your site's build output directory
  functions = "netlify/functions"

redirects
     from = "/api/*"
     to = "/.netlify/functions/:splat"
     status = 200
